name: CICD workflows
on:
  pull_request:
  merge_group:
    branches: [main]
    paths-ignore:
    - .gitignore
    - "Archive/**"
    - "docs/**"

  workflow_dispatch:
    
defaults:
  run:
    shell: pwsh
  
jobs:
  build:
    uses: ./.github/workflows/build.yml

  unit-test:
    uses: ./.github/workflows/unit-test.yml

  # deploy:
  #   uses: ./.github/workflows/deploy.yml