name: CICD workflow
on:
  push:
    branches: [main]
    paths-ignore:
    - .gitignore
    - "Archive/**"
    - "docs/**"

  workflow_dispatch:
    
defaults:
  run:
    shell: pwsh
  
jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml