name: build

on: 
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/build.yml

      - uses: ./.github/workflows/unit-test.yml

      - uses: actions/checkout@v3
        name: Checkout
      
      - name: Deploy
        run: sleep 1m
        shell: bash
      

